name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"
run-name: Build and Release Python Script

jobs:
  build:
    name: Build Executable on Windows
    runs-on: windows-latest

    steps:
      - name: Get code from repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pytubefix
          pip install requests
          pip install mutagen

      - name: Compile Python Code into Executable
        run: |
          pyinstaller yt.py 

      - name: Compress
        run: |
          powershell Compress-Archive -Path dist/* -DestinationPath dist/yt_release.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "pyinstaller_output"
          path: dist/yt_release.zip
          retention-days: 0

  create-release:
    needs: build
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: "pyinstaller_output"
          path: dist/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          artifacts: "dist/yt_release.zip"